/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Description } from './description';
import { Language } from './language';
import { Languagecolour } from './languagecolour';
import { RepoContributor } from './repoContributor';


export interface GitHubRepo { 
    repoName: any | null;
    owner: RepoContributor;
    commitsUrl: any | null;
    visibility: any | null;
    description?: Description;
    updatedAt: any | null;
    language?: Language;
    languageColour?: Languagecolour;
}

